apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: final
  name: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels: 
        app: mysql
    spec: 
      containers:
      - name: frontend-ist
        image: prateekk666/istone-frontend-1.0
        ports:
        - containerPort: 4200