apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: final
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: istone-frontend
        image: prateekk666/istone-frontend-1.0:app
        ports:
        - containerPort: 4200