apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: final
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        label-key : frontend  
    spec:
      containers:
        - name: frontend
          image: prateekk666/istone-frontend-1.0:app
          imagePullPolicy: Always
          ports:
          - containerPort: 4200