apiVersion: v1
kind: Service
metadata:
  namespace: final
  name: frontend-service
spec:
  selector:
    app: istone-frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: LoadBalancer