# java-crud-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: final
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: prateekk666/istone-backend-1.0:app
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "jdbc:mysql://mysql-svc:3306/istdatabase"
        - name: DATABASE_USERNAME
          value: "root"
        - name: DATABASE_PASSWORD
          value: "password"
        