# java-crud-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: final
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: public.ecr.aws/y8u8k9s8/team4/istone:backend-1.0
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "jdbc:mysql://mysql:3306/istdatabase"
        - name: DATABASE_USERNAME
          value: "root"
        - name: DATABASE_PASSWORD
          value: "password"
        