apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: final
  name: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels: 
        app: mysql
    spec: 
      containers:
      - name: database-ist
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env: 
          - name: MYSQL_ROOT_PASSWORD   # Fix: added missing 'name' key
            value: password
          - name: MYSQL_DATABASE        # Fix: added missing 'name' key
            value: istdatabase
          - name: MYSQL_USER            # Fix: added missing 'name' key
            value: user
          - name: MYSQL_PASSWORD        # Fix: added missing 'name' key
            value: userpassword
        volumeMounts:
          - name: mysql-volume          # Fix: corrected volume name here to match the 'volumes' definition
            mountPath: /var/lib/mysql   # Fix: adjusted mount path for mysql storage
      volumes: 
        - name: mysql-volume           # Fix: corrected volume name to match container volumeMount name
          persistentVolumeClaim:
            claimName: mysql-volume-claim
